<a href="https://colab.research.google.com/github/yashyaks/compute_tasks/blob/main/Lab_6/Lab6.2_RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset EDA

In [ ]:
import pandas as pd 

In [ ]:
df = pd.read_csv("/content/sample_data/2011.csv")

In [ ]:
df.head(2)

_STATE  _GEOSTR  _DENSTR2  PRECALL   REPNUM  REPDEPTH  FMONTH        IDATE  \
0     1.0      1.0       1.0      1.0  10001.0      27.0     1.0  b'01202011'   
1     1.0      1.0       1.0      1.0  10008.0      13.0     1.0  b'01142011'   

  IMONTH   IDAY  ... DRNKANY5 DROCDY3_  _RFBING5  _DRNKDY4  _DRNKMO4  \
0  b'01'  b'20'  ...      1.0     43.0       1.0      86.0      26.0   
1  b'01'  b'14'  ...      9.0    900.0       9.0    9900.0    9999.0   

   _RFDRHV4  _RFDRMN4  _RFDRWM4  _AIDTST3  HAVHPAD  
0       1.0       NaN       1.0       2.0      NaN  
1       9.0       9.0       NaN       NaN      NaN  

[2 rows x 454 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1419 entries, 0 to 1418
Columns: 454 entries, _STATE to HAVHPAD
dtypes: float64(444), object(10)
memory usage: 4.9+ MB


In [ ]:
df.isnull().sum().unique()

array([   0,  161,  626,  723,  201, 1257,  724, 1128, 1016, 1406,   46,
       1366, 1085,  495,  481, 1180,   31,   33,   34,   39,   41,   47,
        532,  547,  548, 1013, 1014,   51,   55,   57,  822,  824,  826,
        828,   64,   69,  830, 1015,   73, 1021,   75, 1419,    1, 1274,
        337, 1258, 1415,  162, 1147,  202,   15,   16,   17,   65,   76,
         71,   63,   80,   74,   40,  539,  562,  543,  566,  572, 1025,
        557, 1017,  576,  575,   61,  579,  559,  551,  908,  949,  471])

In [ ]:
df.duplicated().unique()

array([False])

In [ ]:
df.describe()

_STATE      _GEOSTR     _DENSTR2      PRECALL         REPNUM  \
count  1419.0  1419.000000  1419.000000  1419.000000    1419.000000   
mean      1.0    19.715292     2.038055     1.075405   65791.226216   
std       0.0    28.658671     2.513706     0.487453   35715.505324   
min       1.0     1.000000     1.000000     1.000000   10001.000000   
25%       1.0     6.000000     1.000000     1.000000   30171.500000   
50%       1.0     9.000000     1.000000     1.000000   70064.000000   
75%       1.0    15.000000     1.000000     1.000000  100070.000000   
max       1.0    99.000000     9.000000     5.000000  120229.000000   

          REPDEPTH       FMONTH     DISPCODE         SEQNO          _PSU  ...  \
count  1419.000000  1419.000000  1419.000000  1.419000e+03  1.419000e+03  ...   
mean     15.346723     6.568006   110.570825  2.011004e+09  2.011004e+09  ...   
std       8.456702     3.570980     2.320819  2.098642e+03  2.098642e+03  ...   
min       1.000000     1.000000   110.000000  2.011000e+09  2.011000e+09  ...   
25%       8.000000     3.000000   110.000000  2.011002e+09  2.011002e+09  ...   
50%      15.000000     7.000000   110.000000  2.011004e+09  2.011004e+09  ...   
75%      22.000000    10.000000   110.000000  2.011006e+09  2.011006e+09  ...   
max      30.000000    12.000000   120.000000  2.011008e+09  2.011008e+09  ...   

          DRNKANY5      DROCDY3_     _RFBING5      _DRNKDY4      _DRNKMO4  \
count  1418.000000  1.418000e+03  1418.000000  1.418000e+03  1.418000e+03   
mean      2.162906  7.103173e+01     1.675599  7.853745e+02  7.759274e+02   
std       1.791411  2.280975e+02     2.099631  2.633036e+03  2.662567e+03   
min       1.000000  5.397605e-79     1.000000  5.397605e-79  5.397605e-79   
25%       1.000000  5.397605e-79     1.000000  5.397605e-79  5.397605e-79   
50%       2.000000  5.397605e-79     1.000000  5.397605e-79  5.397605e-79   
75%       2.000000  1.000000e+01     1.000000  1.400000e+01  4.000000e+00   
max       9.000000  9.000000e+02     9.000000  9.900000e+03  9.999000e+03   

          _RFDRHV4    _RFDRMN4    _RFDRWM4     _AIDTST3  HAVHPAD  
count  1418.000000  470.000000  948.000000  1345.000000      0.0  
mean      1.648096    1.710638    1.617089     2.141264      NaN  
std       2.129770    2.205173    2.091872     1.827200      NaN  
min       1.000000    1.000000    1.000000     1.000000      NaN  
25%       1.000000    1.000000    1.000000     1.000000      NaN  
50%       1.000000    1.000000    1.000000     2.000000      NaN  
75%       1.000000    1.000000    1.000000     2.000000      NaN  
max       9.000000    9.000000    9.000000     9.000000      NaN  

[8 rows x 444 columns]

In [ ]:
df1 = df

In [ ]:
len(df1.columns)

195

In [ ]:
df1.dropna(subset=['HIVRISK3'],inplace=True)

In [ ]:
df1['HIVRISK3'].isnull().sum()

0

In [ ]:
import numpy as np

In [ ]:
df1.shape[0]

1344

In [ ]:
na_percent = df1.isnull().sum()/df1.shape[0]*100
col_to_drop = na_percent[na_percent>50].keys()
print(col_to_drop)
df1.drop(col_to_drop,axis = 1,inplace = True)

Index([], dtype='object')


In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1344 entries, 0 to 1418
Columns: 195 entries, _STATE to _AIDTST3
dtypes: float64(195)
memory usage: 2.0 MB


In [ ]:
df1.mean()

_STATE          1.000000
_GEOSTR        19.683036
_DENSTR2        2.037202
PRECALL         1.072917
REPNUM      66405.908482
                ...     
_DRNKDY4      305.505585
_DRNKMO4      290.540581
_RFDRHV4        1.260611
_RFDRWM4        1.214047
_AIDTST3        2.141474
Length: 195, dtype: float64

In [ ]:
df1.fillna(df1.mean(), inplace = True)

In [ ]:
df1.isnull().sum().unique()

array([0])

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1344 entries, 0 to 1418
Columns: 195 entries, _STATE to _AIDTST3
dtypes: float64(195)
memory usage: 2.0 MB


In [ ]:
df2=df1.select_dtypes(include=['object'])
df2.head(2)

Empty DataFrame
Columns: []
Index: [0, 2]

In [ ]:
col_to_drop=df2.columns
col_to_drop

Index([], dtype='object')

In [ ]:
df1.drop(col_to_drop,axis = 1,inplace = True)

In [ ]:
df1.head(2)

_STATE  _GEOSTR  _DENSTR2  PRECALL   REPNUM  REPDEPTH  FMONTH  DISPCODE  \
0     1.0      1.0       1.0      1.0  10001.0      27.0     1.0     120.0   
2     1.0      5.0       1.0      1.0  10058.0       4.0     1.0     120.0   

          SEQNO          _PSU  ...  _RFSEAT2  _RFSEAT3  DRNKANY5  DROCDY3_  \
0  2.011000e+09  2.011000e+09  ...       1.0       1.0       1.0      43.0   
2  2.011001e+09  2.011001e+09  ...       1.0       1.0       1.0      14.0   

   _RFBING5  _DRNKDY4  _DRNKMO4  _RFDRHV4  _RFDRWM4  _AIDTST3  
0       1.0      86.0      26.0       1.0       1.0       2.0  
2       1.0      14.0       4.0       1.0       1.0       2.0  

[2 rows x 195 columns]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1344 entries, 0 to 1418
Columns: 195 entries, _STATE to _AIDTST3
dtypes: float64(195)
memory usage: 2.0 MB


In [ ]:
final_col = df1.columns
len(final_col)

195

# Decision Tree without Feature Selection

In [ ]:
X = df1.drop('HIVRISK3',axis = 1)
y = df1['HIVRISK3']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

classifier = DecisionTreeClassifier()

classifier.fit(X_train,y_train)

y_pred_test = classifier.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_test))

Accuracy: 0.948019801980198


# Random Forest without Feature Selection

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9653465346534653


# Feature Selection

In [ ]:
feature_imp = pd.Series(clf.feature_importances_,index=list(final_col[0:-1])).sort_values(ascending=False)
feature_imp

HIVTST6     0.025071
_LLCPM12    0.021851
_REGION     0.019497
HTM4        0.016286
WTKG3       0.014646
              ...   
CTELENUM    0.000000
DISPCODE    0.000000
_VEGESUM    0.000000
PRECALL     0.000000
_STATE      0.000000
Length: 194, dtype: float64

In [ ]:
selected_features = feature_imp[feature_imp>0.01].keys()
selected_features

Index(['HIVTST6', '_LLCPM12', '_REGION', 'HTM4', 'WTKG3', 'HEIGHT3', 'ALCDAY5',
       'FVBEANS', 'AGE', 'FVGREEN', 'METVAL2_', '_PSU', 'REPNUM', 'FRUTDA1_',
       'SEATBELT', 'NATTMPTS', '_AGE_G', '_CNRACEC', 'GENHLTH', 'MAXVO2_',
       'WEIGHT2', 'FRUITJU1', 'VEGETAB1'],
      dtype='object')

In [ ]:
X = df1[selected_features]
y = df1['HIVRISK3']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Decision Tree after Feature Selection

In [ ]:
classifier = DecisionTreeClassifier()

classifier.fit(X_train,y_train)

y_pred_test = classifier.predict(X_test)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_test))

Accuracy: 0.943069306930693


# Random Forest after Feature Selection

In [ ]:
clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9752475247524752
