#### Import NumPy 

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
a = np.ones(10)*5

#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
a = []
for i in range(10,51):
  a.append(i)
print(a)


[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
a = []
for i in range(10,51,2):
  a.append(i)
print(a)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [ ]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
a = np.random(0,1)


TypeError: ignored

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

#### Create the following matrix: -!del!-

#### Create an array of 20 linearly spaced points between 0 and 1: 

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
a = np.arange(12,25).reshape(3,3)

ValueError: ignored

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
a = 20
print(a)

20


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
a = np.arange(21,26)
print(a)

[21 22 23 24 25]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
a = np.arange(16,26).reshape(2,5)
a

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [34]:
a = ([0,325],[0,0])
print(np.sum(a))

325


#### Get the standard deviation of the values in mat

In [35]:
a = ([0,325],[0,0])
print(np.std(a))

140.72912811497127


#### Get the sum of all the columns in mat

In [39]:
a = ([0,325],[0,1])
print(np.sum(a,axis=0))

[  0 326]


#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [45]:
A = ([1, 2], [2, 3])
B = ([4, 5], [6, 7])

result = np.dot(A,B)
print(result)

[[16 19]
 [26 31]]


####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [55]:
#pandas?
import pandas as pd
#a = [[ 1.3, 2.5, 3.6, np.nan] [ 2.6, 3.3, np.nan, 5.5] [ 2.1, 3.2, 5.4, 6.5]]
df = pd.DataFrame(
     [[ 1.3, 2.5, 3.6, np.nan], [ 2.6, 3.3, np.nan, 5.5], [ 2.1, 3.2, 5.4, 6.5]]
)

df.fillna(value=df.mean())
print(df)


     0    1    2    3
0  1.3  2.5  3.6  NaN
1  2.6  3.3  NaN  5.5
2  2.1  3.2  5.4  6.5


# You're done!